# Generated by Django 2.1.7 on 2019-04-11 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reg_no', models.DecimalField(decimal_places=0, max_digits=8, unique=True, verbose_name='reg_no')),
                ('user_email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('user_name', models.CharField(max_length=100, verbose_name='name')),
                ('user_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('user_cpi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='cpi')),
                ('user_bio', models.CharField(max_length=1000, verbose_name='bio')),
                ('user_contact', models.CharField(max_length=15, verbose_name='contact')),
                ('authority', models.IntegerField(default=0, verbose_name='authority')),
                ('email_verified', models.IntegerField(default=0, verbose_name='email_verified')),
                ('data_verified', models.IntegerField(default=0, verbose_name='data_verified')),
                ('user_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
