# Generated by Django 2.1.7 on 2019-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_bio',
            field=models.TextField(max_length=1000, verbose_name='bio'),
        ),
    ]
