# Generated by Django 2.1.7 on 2019-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190411_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Prefer Not To Say')], max_length=1),
        ),
    ]
