# Generated by Django 2.1.7 on 2019-04-13 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190413_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='team_name')),
                ('team_cpi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='cpi')),
                ('team_leader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('team_member_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to=settings.AUTH_USER_MODEL)),
                ('team_member_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3', to=settings.AUTH_USER_MODEL)),
                ('team_member_4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
