# Generated by Django 2.1.7 on 2019-04-16 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_user_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_details',
            name='team_member_4',
        ),
        migrations.AddField(
            model_name='team_details',
            name='team_member_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team_details',
            name='team_leader',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
