# Generated by Django 2.1.7 on 2019-04-19 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20190416_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_priority', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='priority')),
                ('proff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='_proff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
