# Generated by Django 2.1.7 on 2019-04-11 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_content', models.CharField(max_length=500, verbose_name='content')),
                ('notification_user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Team_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='team_name')),
                ('team_cpi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='cpi')),
                ('team_leader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('team_member_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to=settings.AUTH_USER_MODEL)),
                ('team_member_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3', to=settings.AUTH_USER_MODEL)),
                ('team_member_4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
